### ISSUE TITLE
Support for Unicode box drawing characters

### ISSUE THREAD

**Issue by alexey-milovidov** [AlexanderGrooff/mermaid-ascii#16]
I'd like to have more than ASCII.

**Comment by AlexanderGrooff** [comment]
What would you like to see? Do you have some examples that you would expect to work, but don't?

**Comment by bAndie91** [comment]
i second this wish item.
plus add all 9 type of box drawing chars (which i'm currently aware of)…
and can specify each node/edge which style to use…

```
║ U+2551 BOX DRAWINGS DOUBLE VERTICAL

│ U+2502 BOX DRAWINGS LIGHT VERTICAL
┃ U+2503 BOX DRAWINGS HEAVY VERTICAL

╎ U+254E BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL
╏ U+254F BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL

┆ U+2506 BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
┇ U+2507 BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL

┊ U+250A BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
┋ U+250B BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
```

**Comment by bAndie91** [comment]
it would be definitely the right way to add it as an option besides plain ascii.

**Comment by AlexanderGrooff** [comment]
Added support to toggle between extended box characters and the previous ASCII drawings in both the interface and CLI with `--ascii`
