### ISSUE TITLE
Text overwritten by path

### ISSUE THREAD

**Issue by BonHammer** [AlexanderGrooff/mermaid-ascii#19]
Hello, your tool seems very useful for producing short comments on LADDER as web links that can generate complex sequential function chart used in industrial PLC's so I tried a few options and this error happens frequent enough that I should share. The texts in-between | | sometimes gets replaced with the path of the arrows instead.

This input:
graph TD
00 -->|&b0.05| 01 -->|&b0.04| 02 -->|&b0.08| 03 -->|&b0.14| 00

Creates this output:
+--------+ 
|        | 
|   00   | 
|        | 
+--------+ 
     ^     
  &b0|05   
     |-----
     v    |
+--------+|
|        ||
|   01   ||
|        ||
+--------+|
     |    |
  &b0.04  |
     |    |
     v    |
+--------+|
|        ||
|   02   ||
|        ||
+--------+|
     |    |
  &b0.08  |
     -----|
  &b0.14   
+--------+ 
|        | 
|   03   | 
|        | 
+--------+ 

Where the "&b0|05" should be "&b0.05".

Also, when creating linear graphs like theses, it would help electricians a lot if the arrow came from the bottom of the last box to the top or side of the first box instead of currently linking paths.

**Comment by AlexanderGrooff** [comment]
Hi there, thanks for the bug report. I've made some changes in 0.5.1 that should alleviate some of the issues you mentioned. I now draw out the labels as the last step, instead of drawing arrows over the labels. Your graph looks like this now:

```
+--------+  
|        |  
|   00   |  
|        |  
+--------+  
     ^      
     |      
  &b0.05---+
     |     |
     v     |
+--------+ |
|        | |
|   01   | |
|        | |
+--------+ |
     |     |
     |     |
  &b0.04   |
     |     |
     v     |
+--------+ |
|        | |
|   02   | |
|        | |
+--------+ |
     |     |
     |     |
  &b0.08---+
  &b0.14    
     v      
+--------+  
|        |  
|   03   |  
|        |  
+--------+  
```

As you mentioned, the pathing is not perfect yet, but I hope this already helps you out a bit.
